spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bankdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123456789}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: ${PORT:8080}
app:
  jwt-secret: ${JWT_SECRET:change-me-very-secure-and-long-length-required}
  jwt-expiration-ms: 86400000
